code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension batisteo.vscode-django
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-extension-pack
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eriklynd.json-tools
code --install-extension ffaraone.pyfilesgen
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension kiteco.kite
code --install-extension magicstack.MagicPython
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ru
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension p1c2u.docker-compose
code --install-extension rebornix.project-snippets
code --install-extension Remisa.shellman
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rogalmic.bash-debug
code --install-extension thebarkman.vscode-djaneiro
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wholroyd.jinja
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion